server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true

  #Live Reload 기능 활성화
  thymeleaf:
    cache: false

  servlet:
    multipart:
      # 파일 한 개당 최대 사이즈
      max-file-size: 20MB
      # 요청당 최대 파일 크기
      max-request-size: 100MB

#상품 이미지 업로드 경로
itemImgLocation: c:/shop/item

#리소드 이미지 업로드 경로
uploadPath: file:///C:/shop/

#Thymeleaf cache 사용 중지

# 쿼리에 물음표로 출력되는 바인드 파라미터 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
